{{- $applications := list .Values.front -}}
{{ range $applications }}
{{- $name := .name -}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
  labels:
    app: {{ $name }}
    app.kubernetes.io/name: {{ $name }}
spec:
  replicas: {{ .replicaCount }}
  selector:
    matchLabels:
      app: {{ $name }}
      app.kubernetes.io/name: {{ $name }}
  template:
    metadata:
      labels:
        app: {{ $name }}
        app.kubernetes.io/name: {{ $name }}
        {{- if .additionalPodLabels }}
        {{- toYaml .additionalPodLabels | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: webapp
          image: "{{ .image }}:{{ .tag }}"
          imagePullPolicy: Always
          env:
            - name: MONGO_HOST
              value: "{{ .db.host }}"
            - name: MONGO_PORT
              value: "{{ .db.port }}"
            - name: MONGO_USER
              value: "{{ .db.username }}"
            - name: MONGO_PASS
              value: "{{ .db.userpwd }}"
            - name: MONGO_TLS
              value: "{{ .db.tls }}"
          ports:
            - name: http
              containerPort: {{ .containerPort }}
              protocol: TCP
          resources:
            {{- toYaml .resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: {{ .healthEndpoint }}
              port: {{ .containerPort }}
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 15
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: {{ .healthEndpoint }}
              port: {{ .containerPort }}
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 1
{{ end }}
