# Installs Rancher with a certificate generated by a cluster issuer
# -----------------------------------------------------------------
# Arguments:
#   - Rancher Helm repository suffix (latest, stable)
#   - Rancher version
#   - Number of replicas
#   - Hostname
#   - Cluster issuer name (managed by cert-manager)
# Examples
#   - install_rancher_externalclusterissuer latest "2.8.2" 1 rancher.random_string.geek letsencrypt-prod
install_rancher_externalclusterissuer() {
  local repository=$1
  local version=$2
  local replicas=$3
  local hostname=$4
  local clusterissuer=$5

  echo "Installing Rancher..."
  helm repo add rancher-${repository} https://releases.rancher.com/server-charts/${repository}
  helm repo update
  helm upgrade --install rancher rancher-${repository}/rancher --namespace cattle-system --create-namespace \
    --version ${version} \
    --set replicas=${replicas} \
    --set hostname=${hostname} \
    --set ingress.extraAnnotations.'cert-manager\.io/cluster-issuer'=${clusterissuer} \
    --set ingress.tls.source=secret \
    --set ingress.tls.secretName=rancher-tls
  kubectl wait pods -n cattle-system -l app=rancher --for condition=Ready --timeout=180s
  while ! kubectl get secret rancher-tls --namespace cattle-system; do sleep 1; done
  sleep 10
}
