---
apiVersion: v1
kind: Secret
metadata:
  name: dirsrv-tls-secret
#  namespace: {{ .Values.ds389.nsName }}
data:
  tls.key: {{ .Values.ds389.tlsKey | b64enc | quote }}
  tls.crt: {{ .Values.ds389.tlsCert | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: dirsrv-dm-password
#  namespace: {{ .Values.ds389.nsName }}
data:
  dm-password: {{ .Values.ds389.dmPassword | quote }}
