apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.ds389.name }}
  name: {{ .Values.ds389.name }}-external-svc
#  namespace: {{ .Values.ds389.nsName }}
spec:
  ports:
    - name: {{ .Values.ds389.name }}-port
      port: {{ .Values.ds389.internalPort }}
      protocol: TCP
      targetPort: {{ .Values.ds389.internalPort }}
      nodePort: {{ .Values.ds389.nodePort }}
    - name: {{ .Values.ds389.name }}-tls-port
      port: {{ .Values.ds389.tlsPort }}
      protocol: TCP
      targetPort: {{ .Values.ds389.tlsPort }}
      nodePort: {{ .Values.ds389.nodePortTls }}
  selector:
    app: {{ .Values.ds389.name }}
  type: NodePort

