apiVersion: v2
name: nfs-ganesha
description: Helm chart for managing NFS-Ganesha
type: application
version: "0.1.0"
appVersion: "1.0.0"
dependencies: []
home: https://github.com/SUSE/lab-setup/tree/main/charts/nfs-ganesha
maintainers:
  - name: devpro
    email: bertrand.thomas@suse.com
