name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - develop
  schedule:
    - cron: "0 2 * * 1-5"
  workflow_dispatch: {}

jobs:
  code-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checks-out the repository
        uses: actions/checkout@v4
      - name: Lints Markdown files
        uses: DavidAnson/markdownlint-cli2-action@v16
        with:
          globs: '**/*.md'
      - name: Installs packages
        run: sudo apt install shellcheck
      - name: Checks shell file code
        run:
          shellcheck scripts/**/*.sh
